In [4]:
import tensorflow as tf
print(tf.version)


<module 'tensorflow._api.v2.version' from '/opt/conda/envs/ds-and-ml/lib/python3.9/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [7]:
t  = tf.ones([2,2,2]) # create a tensor of ones with shape [2,2,2]
t

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [9]:
# flattens the tensor to 1D
tf.reshape(t, [8])

<tf.Tensor: shape=(8,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [10]:
# -1 means "whatever size is needed" to maintain the number of elements
tf.reshape(t, [2, -1])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>